networks:
  backend:

services:
  gamedb:
    container_name: game-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=password@12345#
    networks:
      - backend
    ports:
      - "8011:1433" 

  game.webapi:
    container_name: Game-api
    image: ${DOCKER_REGISTRY-}gamewebapi
    build:
      context: .
      dockerfile: src/Game.WebAPI/Dockerfile
    networks:
      - backend
    environment:
      - ConnectionStrings__DefaultConnection=Server=Gamedb;Database=GameDb;User Id=sa;Password=password@12345#;TrustServerCertificate=True;
    depends_on:
      - gamedb
    ports:
      - "8012:80"
      - "8092:443"

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - backend
  
  library-redis:
    image: "redis:latest"
    restart: always
    ports:
      - "6379:6379"
    networks:
      - backend
