version: '3.4'

networks:
  backend:

services:
  authdb:
    container_name: Auth-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=password@12345#
    networks:
      - backend
    ports:
      - "8001:1433" 

  auth.api:
    container_name: auth-api
    image: ${DOCKER_REGISTRY-}authapi
    build:
      context: .
      dockerfile: src/Auth.API/Dockerfile
    networks:
      - backend
    environment:
      - Jwt__Secret=superSecretKey@345432242344324245
      - Jwt__Issuer=https://localhost:5001
      - Jwt__Audience=https://localhost:5001
      - Jwt__TokenValidityInMinutes=30
      - ConnectionStrings__DefaultConnection=Server=authdb;Database=AuthDb;User Id=sa;Password=password@12345#;TrustServerCertificate=True;
    depends_on:
      - authdb
    ports:
      - "8002:80"
      - "8082:443"
